"""initial schema

Revision ID: b8fba877bac2
Revises: 
Create Date: 2026-08-29 11:47:06.906236
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b8fba877bac2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('role', sa.Enum('DONOR', 'MEMBER', 'OFFICE', name='role', native_enum=False), nullable=False),
    sa.Column('dong', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('appointed_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('need_summary', sa.String(length=160), nullable=False),
    sa.Column('situation_note', sa.Text(), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MATCHING', 'RESOLVED', 'CLOSED', name='casestatus', native_enum=False), nullable=False),
    sa.Column('public_support_linked', sa.Boolean(), nullable=False),
    sa.Column('public_support_note', sa.Text(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_case_is_urgent'), ['is_urgent'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_status'), ['status'], unique=False)

    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('VOLUNTEER', 'DONATION', name='creditkind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ISSUED', 'REJECTED', name='creditstatus', native_enum=False), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=False),
    sa.Column('volunteer_hours', sa.Integer(), nullable=True),
    sa.Column('amount_krw', sa.Integer(), nullable=True),
    sa.Column('issued_note', sa.Text(), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_donor_id'), ['donor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_status'), ['status'], unique=False)

    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('walk_minutes', sa.Integer(), nullable=True),
    sa.Column('is_certified', sa.Boolean(), nullable=False),
    sa.Column('certified_by_id', sa.Integer(), nullable=True),
    sa.Column('certified_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['certified_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('case_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name_enc', sa.Text(), nullable=True),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('address_enc', sa.Text(), nullable=True),
    sa.Column('consult_note_enc', sa.Text(), nullable=True),
    sa.Column('consent_obtained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_identity_case_id'), ['case_id'], unique=True)

    op.create_table('identity_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_access_log_accessed_at'), ['accessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_log_case_id'), ['case_id'], unique=False)

    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('GOODS', 'SERVICE', 'MEAL', 'REPAIR', name='offerkind', native_enum=False), nullable=False),
    sa.Column('icon', sa.String(length=24), nullable=False),
    sa.Column('quantity_note', sa.String(length=160), nullable=True),
    sa.Column('delivery', sa.Enum('MEMBER_PICKUP', 'BENEFICIARY_VISIT', 'DELIVERY', name='deliverymethod', native_enum=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESERVED', 'CLOSED', name='offerstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_status'), ['status'], unique=False)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'DELIVERED', 'CANCELLED', name='matchstatus', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_proposed_by_id'), ['proposed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_status'), ['status'], unique=False)

    op.create_table('match_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'approver_id', name='uq_match_approver')
    )
    with op.batch_alter_table('match_approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_approval_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_approval_match_id'), ['match_id'], unique=False)

    op.create_table('thanks_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('written_by_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['written_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thanks_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thanks_message_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thanks_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thanks_message_match_id'))

    op.drop_table('thanks_message')
    with op.batch_alter_table('match_approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_approval_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_approval_approver_id'))

    op.drop_table('match_approval')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_status'))
        batch_op.drop_index(batch_op.f('ix_match_proposed_by_id'))
        batch_op.drop_index(batch_op.f('ix_match_offer_id'))
        batch_op.drop_index(batch_op.f('ix_match_case_id'))

    op.drop_table('match')
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_status'))
        batch_op.drop_index(batch_op.f('ix_offer_shop_id'))
        batch_op.drop_index(batch_op.f('ix_offer_kind'))

    op.drop_table('offer')
    with op.batch_alter_table('identity_access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_access_log_case_id'))
        batch_op.drop_index(batch_op.f('ix_identity_access_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_identity_access_log_accessed_at'))

    op.drop_table('identity_access_log')
    with op.batch_alter_table('case_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_identity_case_id'))

    op.drop_table('case_identity')
    op.drop_table('shop')
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_status'))
        batch_op.drop_index(batch_op.f('ix_credit_donor_id'))

    op.drop_table('credit')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_status'))
        batch_op.drop_index(batch_op.f('ix_case_member_id'))
        batch_op.drop_index(batch_op.f('ix_case_is_urgent'))
        batch_op.drop_index(batch_op.f('ix_case_code'))

    op.drop_table('case')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
